/// País con su nombre, código ISO-3166-1 alpha-2 (para la bandera emoji) y
/// prefijo telefónico internacional.
class Pais {
  final String nombre;
  final String iso;
  final String codigo;

  const Pais({
    required this.nombre,
    required this.iso,
    required this.codigo,
  });

  /// Bandera emoji generada a partir del código ISO de dos letras.
  String get bandera {
    const base = 0x1F1E6 - 65; // 'A' -> U+1F1E6 (regional indicator A)
    return String.fromCharCodes(
      iso.toUpperCase().codeUnits.map((u) => base + u),
    );
  }

  /// Texto compacto para mostrar en el selector: "🇧🇴 Bolivia (+591)".
  String get etiqueta => '$bandera $nombre ($codigo)';

  /// Texto corto para chips: "🇧🇴 +591".
  String get corto => '$bandera $codigo';
}

/// Lista de países soportados para el selector de código de país.
/// Ordenados con los de habla hispana/principal mercado primero y luego
/// alfabéticamente por nombre.
const List<Pais> paises = [
  Pais(nombre: 'Bolivia', iso: 'BO', codigo: '+591'),
  Pais(nombre: 'Argentina', iso: 'AR', codigo: '+54'),
  Pais(nombre: 'Chile', iso: 'CL', codigo: '+56'),
  Pais(nombre: 'Colombia', iso: 'CO', codigo: '+57'),
  Pais(nombre: 'Costa Rica', iso: 'CR', codigo: '+506'),
  Pais(nombre: 'Cuba', iso: 'CU', codigo: '+53'),
  Pais(nombre: 'Ecuador', iso: 'EC', codigo: '+593'),
  Pais(nombre: 'El Salvador', iso: 'SV', codigo: '+503'),
  Pais(nombre: 'España', iso: 'ES', codigo: '+34'),
  Pais(nombre: 'Estados Unidos', iso: 'US', codigo: '+1'),
  Pais(nombre: 'Guatemala', iso: 'GT', codigo: '+502'),
  Pais(nombre: 'Honduras', iso: 'HN', codigo: '+504'),
  Pais(nombre: 'México', iso: 'MX', codigo: '+52'),
  Pais(nombre: 'Nicaragua', iso: 'NI', codigo: '+505'),
  Pais(nombre: 'Panamá', iso: 'PA', codigo: '+507'),
  Pais(nombre: 'Paraguay', iso: 'PY', codigo: '+595'),
  Pais(nombre: 'Perú', iso: 'PE', codigo: '+51'),
  Pais(nombre: 'Puerto Rico', iso: 'PR', codigo: '+1'),
  Pais(nombre: 'República Dominicana', iso: 'DO', codigo: '+1'),
  Pais(nombre: 'Uruguay', iso: 'UY', codigo: '+598'),
  Pais(nombre: 'Venezuela', iso: 'VE', codigo: '+58'),
  Pais(nombre: 'Brasil', iso: 'BR', codigo: '+55'),
  Pais(nombre: 'Afganistán', iso: 'AF', codigo: '+93'),
  Pais(nombre: 'Albania', iso: 'AL', codigo: '+355'),
  Pais(nombre: 'Alemania', iso: 'DE', codigo: '+49'),
  Pais(nombre: 'Andorra', iso: 'AD', codigo: '+376'),
  Pais(nombre: 'Angola', iso: 'AO', codigo: '+244'),
  Pais(nombre: 'Antigua y Barbuda', iso: 'AG', codigo: '+1'),
  Pais(nombre: 'Arabia Saudita', iso: 'SA', codigo: '+966'),
  Pais(nombre: 'Argelia', iso: 'DZ', codigo: '+213'),
  Pais(nombre: 'Armenia', iso: 'AM', codigo: '+374'),
  Pais(nombre: 'Australia', iso: 'AU', codigo: '+61'),
  Pais(nombre: 'Austria', iso: 'AT', codigo: '+43'),
  Pais(nombre: 'Azerbaiyán', iso: 'AZ', codigo: '+994'),
  Pais(nombre: 'Bahamas', iso: 'BS', codigo: '+1'),
  Pais(nombre: 'Bangladés', iso: 'BD', codigo: '+880'),
  Pais(nombre: 'Barbados', iso: 'BB', codigo: '+1'),
  Pais(nombre: 'Baréin', iso: 'BH', codigo: '+973'),
  Pais(nombre: 'Bélgica', iso: 'BE', codigo: '+32'),
  Pais(nombre: 'Belice', iso: 'BZ', codigo: '+501'),
  Pais(nombre: 'Benín', iso: 'BJ', codigo: '+229'),
  Pais(nombre: 'Bielorrusia', iso: 'BY', codigo: '+375'),
  Pais(nombre: 'Birmania', iso: 'MM', codigo: '+95'),
  Pais(nombre: 'Bosnia y Herzegovina', iso: 'BA', codigo: '+387'),
  Pais(nombre: 'Botsuana', iso: 'BW', codigo: '+267'),
  Pais(nombre: 'Bulgaria', iso: 'BG', codigo: '+359'),
  Pais(nombre: 'Burkina Faso', iso: 'BF', codigo: '+226'),
  Pais(nombre: 'Burundi', iso: 'BI', codigo: '+257'),
  Pais(nombre: 'Bután', iso: 'BT', codigo: '+975'),
  Pais(nombre: 'Cabo Verde', iso: 'CV', codigo: '+238'),
  Pais(nombre: 'Camboya', iso: 'KH', codigo: '+855'),
  Pais(nombre: 'Camerún', iso: 'CM', codigo: '+237'),
  Pais(nombre: 'Canadá', iso: 'CA', codigo: '+1'),
  Pais(nombre: 'Catar', iso: 'QA', codigo: '+974'),
  Pais(nombre: 'Chad', iso: 'TD', codigo: '+235'),
  Pais(nombre: 'China', iso: 'CN', codigo: '+86'),
  Pais(nombre: 'Chipre', iso: 'CY', codigo: '+357'),
  Pais(nombre: 'Ciudad del Vaticano', iso: 'VA', codigo: '+39'),
  Pais(nombre: 'Comoras', iso: 'KM', codigo: '+269'),
  Pais(nombre: 'Corea del Norte', iso: 'KP', codigo: '+850'),
  Pais(nombre: 'Corea del Sur', iso: 'KR', codigo: '+82'),
  Pais(nombre: 'Costa de Marfil', iso: 'CI', codigo: '+225'),
  Pais(nombre: 'Croacia', iso: 'HR', codigo: '+385'),
  Pais(nombre: 'Dinamarca', iso: 'DK', codigo: '+45'),
  Pais(nombre: 'Dominica', iso: 'DM', codigo: '+1'),
  Pais(nombre: 'Egipto', iso: 'EG', codigo: '+20'),
  Pais(nombre: 'Emiratos Árabes Unidos', iso: 'AE', codigo: '+971'),
  Pais(nombre: 'Eritrea', iso: 'ER', codigo: '+291'),
  Pais(nombre: 'Eslovaquia', iso: 'SK', codigo: '+421'),
  Pais(nombre: 'Eslovenia', iso: 'SI', codigo: '+386'),
  Pais(nombre: 'Estonia', iso: 'EE', codigo: '+372'),
  Pais(nombre: 'Eswatini', iso: 'SZ', codigo: '+268'),
  Pais(nombre: 'Etiopía', iso: 'ET', codigo: '+251'),
  Pais(nombre: 'Filipinas', iso: 'PH', codigo: '+63'),
  Pais(nombre: 'Finlandia', iso: 'FI', codigo: '+358'),
  Pais(nombre: 'Fiyi', iso: 'FJ', codigo: '+679'),
  Pais(nombre: 'Francia', iso: 'FR', codigo: '+33'),
  Pais(nombre: 'Gabón', iso: 'GA', codigo: '+241'),
  Pais(nombre: 'Gambia', iso: 'GM', codigo: '+220'),
  Pais(nombre: 'Georgia', iso: 'GE', codigo: '+995'),
  Pais(nombre: 'Ghana', iso: 'GH', codigo: '+233'),
  Pais(nombre: 'Granada', iso: 'GD', codigo: '+1'),
  Pais(nombre: 'Grecia', iso: 'GR', codigo: '+30'),
  Pais(nombre: 'Guinea', iso: 'GN', codigo: '+224'),
  Pais(nombre: 'Guinea-Bisáu', iso: 'GW', codigo: '+245'),
  Pais(nombre: 'Guinea Ecuatorial', iso: 'GQ', codigo: '+240'),
  Pais(nombre: 'Guyana', iso: 'GY', codigo: '+592'),
  Pais(nombre: 'Haití', iso: 'HT', codigo: '+509'),
  Pais(nombre: 'Hungría', iso: 'HU', codigo: '+36'),
  Pais(nombre: 'India', iso: 'IN', codigo: '+91'),
  Pais(nombre: 'Indonesia', iso: 'ID', codigo: '+62'),
  Pais(nombre: 'Irak', iso: 'IQ', codigo: '+964'),
  Pais(nombre: 'Irán', iso: 'IR', codigo: '+98'),
  Pais(nombre: 'Irlanda', iso: 'IE', codigo: '+353'),
  Pais(nombre: 'Islandia', iso: 'IS', codigo: '+354'),
  Pais(nombre: 'Islas Marshall', iso: 'MH', codigo: '+692'),
  Pais(nombre: 'Islas Salomón', iso: 'SB', codigo: '+677'),
  Pais(nombre: 'Israel', iso: 'IL', codigo: '+972'),
  Pais(nombre: 'Italia', iso: 'IT', codigo: '+39'),
  Pais(nombre: 'Jamaica', iso: 'JM', codigo: '+1'),
  Pais(nombre: 'Japón', iso: 'JP', codigo: '+81'),
  Pais(nombre: 'Jordania', iso: 'JO', codigo: '+962'),
  Pais(nombre: 'Kazajistán', iso: 'KZ', codigo: '+7'),
  Pais(nombre: 'Kenia', iso: 'KE', codigo: '+254'),
  Pais(nombre: 'Kirguistán', iso: 'KG', codigo: '+996'),
  Pais(nombre: 'Kiribati', iso: 'KI', codigo: '+686'),
  Pais(nombre: 'Kuwait', iso: 'KW', codigo: '+965'),
  Pais(nombre: 'Laos', iso: 'LA', codigo: '+856'),
  Pais(nombre: 'Lesoto', iso: 'LS', codigo: '+266'),
  Pais(nombre: 'Letonia', iso: 'LV', codigo: '+371'),
  Pais(nombre: 'Líbano', iso: 'LB', codigo: '+961'),
  Pais(nombre: 'Liberia', iso: 'LR', codigo: '+231'),
  Pais(nombre: 'Libia', iso: 'LY', codigo: '+218'),
  Pais(nombre: 'Liechtenstein', iso: 'LI', codigo: '+423'),
  Pais(nombre: 'Lituania', iso: 'LT', codigo: '+370'),
  Pais(nombre: 'Luxemburgo', iso: 'LU', codigo: '+352'),
  Pais(nombre: 'Madagascar', iso: 'MG', codigo: '+261'),
  Pais(nombre: 'Malasia', iso: 'MY', codigo: '+60'),
  Pais(nombre: 'Malaui', iso: 'MW', codigo: '+265'),
  Pais(nombre: 'Maldivas', iso: 'MV', codigo: '+960'),
  Pais(nombre: 'Malí', iso: 'ML', codigo: '+223'),
  Pais(nombre: 'Malta', iso: 'MT', codigo: '+356'),
  Pais(nombre: 'Marruecos', iso: 'MA', codigo: '+212'),
  Pais(nombre: 'Mauricio', iso: 'MU', codigo: '+230'),
  Pais(nombre: 'Mauritania', iso: 'MR', codigo: '+222'),
  Pais(nombre: 'Micronesia', iso: 'FM', codigo: '+691'),
  Pais(nombre: 'Moldavia', iso: 'MD', codigo: '+373'),
  Pais(nombre: 'Mónaco', iso: 'MC', codigo: '+377'),
  Pais(nombre: 'Mongolia', iso: 'MN', codigo: '+976'),
  Pais(nombre: 'Montenegro', iso: 'ME', codigo: '+382'),
  Pais(nombre: 'Mozambique', iso: 'MZ', codigo: '+258'),
  Pais(nombre: 'Namibia', iso: 'NA', codigo: '+264'),
  Pais(nombre: 'Nauru', iso: 'NR', codigo: '+674'),
  Pais(nombre: 'Nepal', iso: 'NP', codigo: '+977'),
  Pais(nombre: 'Nicaragua', iso: 'NI', codigo: '+505'),
  Pais(nombre: 'Níger', iso: 'NE', codigo: '+227'),
  Pais(nombre: 'Nigeria', iso: 'NG', codigo: '+234'),
  Pais(nombre: 'Noruega', iso: 'NO', codigo: '+47'),
  Pais(nombre: 'Nueva Zelanda', iso: 'NZ', codigo: '+64'),
  Pais(nombre: 'Omán', iso: 'OM', codigo: '+968'),
  Pais(nombre: 'Países Bajos', iso: 'NL', codigo: '+31'),
  Pais(nombre: 'Pakistán', iso: 'PK', codigo: '+92'),
  Pais(nombre: 'Palaos', iso: 'PW', codigo: '+680'),
  Pais(nombre: 'Palestina', iso: 'PS', codigo: '+970'),
  Pais(nombre: 'Papúa Nueva Guinea', iso: 'PG', codigo: '+675'),
  Pais(nombre: 'Polonia', iso: 'PL', codigo: '+48'),
  Pais(nombre: 'Portugal', iso: 'PT', codigo: '+351'),
  Pais(nombre: 'Reino Unido', iso: 'GB', codigo: '+44'),
  Pais(nombre: 'Ruanda', iso: 'RW', codigo: '+250'),
  Pais(nombre: 'Rumania', iso: 'RO', codigo: '+40'),
  Pais(nombre: 'Rusia', iso: 'RU', codigo: '+7'),
  Pais(nombre: 'Samoa', iso: 'WS', codigo: '+685'),
  Pais(nombre: 'San Cristóbal y Nieves', iso: 'KN', codigo: '+1'),
  Pais(nombre: 'San Marino', iso: 'SM', codigo: '+378'),
  Pais(nombre: 'San Vicente y las Granadinas', iso: 'VC', codigo: '+1'),
  Pais(nombre: 'Santa Lucía', iso: 'LC', codigo: '+1'),
  Pais(nombre: 'Santo Tomé y Príncipe', iso: 'ST', codigo: '+239'),
  Pais(nombre: 'Senegal', iso: 'SN', codigo: '+221'),
  Pais(nombre: 'Serbia', iso: 'RS', codigo: '+381'),
  Pais(nombre: 'Seychelles', iso: 'SC', codigo: '+248'),
  Pais(nombre: 'Sierra Leona', iso: 'SL', codigo: '+232'),
  Pais(nombre: 'Singapur', iso: 'SG', codigo: '+65'),
  Pais(nombre: 'Siria', iso: 'SY', codigo: '+963'),
  Pais(nombre: 'Somalia', iso: 'SO', codigo: '+252'),
  Pais(nombre: 'Sri Lanka', iso: 'LK', codigo: '+94'),
  Pais(nombre: 'Sudáfrica', iso: 'ZA', codigo: '+27'),
  Pais(nombre: 'Sudán', iso: 'SD', codigo: '+249'),
  Pais(nombre: 'Sudán del Sur', iso: 'SS', codigo: '+211'),
  Pais(nombre: 'Suecia', iso: 'SE', codigo: '+46'),
  Pais(nombre: 'Suiza', iso: 'CH', codigo: '+41'),
  Pais(nombre: 'Surinam', iso: 'SR', codigo: '+597'),
  Pais(nombre: 'Tailandia', iso: 'TH', codigo: '+66'),
  Pais(nombre: 'Tanzania', iso: 'TZ', codigo: '+255'),
  Pais(nombre: 'Tayikistán', iso: 'TJ', codigo: '+992'),
  Pais(nombre: 'Timor Oriental', iso: 'TL', codigo: '+670'),
  Pais(nombre: 'Togo', iso: 'TG', codigo: '+228'),
  Pais(nombre: 'Tonga', iso: 'TO', codigo: '+676'),
  Pais(nombre: 'Trinidad y Tobago', iso: 'TT', codigo: '+1'),
  Pais(nombre: 'Túnez', iso: 'TN', codigo: '+216'),
  Pais(nombre: 'Turkmenistán', iso: 'TM', codigo: '+993'),
  Pais(nombre: 'Turquía', iso: 'TR', codigo: '+90'),
  Pais(nombre: 'Tuvalu', iso: 'TV', codigo: '+688'),
  Pais(nombre: 'Ucrania', iso: 'UA', codigo: '+380'),
  Pais(nombre: 'Uganda', iso: 'UG', codigo: '+256'),
  Pais(nombre: 'Uzbekistán', iso: 'UZ', codigo: '+998'),
  Pais(nombre: 'Vanuatu', iso: 'VU', codigo: '+678'),
  Pais(nombre: 'Yemen', iso: 'YE', codigo: '+967'),
  Pais(nombre: 'Yibuti', iso: 'DJ', codigo: '+253'),
  Pais(nombre: 'Zambia', iso: 'ZM', codigo: '+260'),
  Pais(nombre: 'Zimbabue', iso: 'ZW', codigo: '+263'),
];

/// Busca un país por su código numérico (ej. `+591`).
Pais? paisPorCodigo(String? codigo) {
  if (codigo == null || codigo.isEmpty) return null;
  final limpio = codigo.trim();
  return paises.cast<Pais?>().firstWhere(
        (p) => p!.codigo == limpio,
        orElse: () => null,
      );
}
